# Generated by Django 5.2.6 on 2025-09-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('local', 'Local'), ('national', 'National'), ('state', 'State'), ('international', 'International')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('local', 'Local'), ('national', 'National'), ('state', 'State'), ('international', 'International')], max_length=20)),
                ('indicator', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('forecast', models.FloatField()),
                ('confidence', models.IntegerField()),
                ('range_low', models.FloatField()),
                ('range_high', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EconomicMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('local', 'Local'), ('national', 'National'), ('state', 'State'), ('international', 'International')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('change', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('trend', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('stable', 'stable')], max_length=10)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('local', 'Local'), ('national', 'National'), ('state', 'State'), ('international', 'International')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
