# Generated by Django 5.2.6 on 2025-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_funding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('conditional', 'Conditional')], max_length=20)),
                ('description', models.TextField()),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('generated_content', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlanSection',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('recommendations', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField()),
                ('application_process', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DebtImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_flow_impact', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collateral_risk', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EquityImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilution', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ownership_retained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('control_impact', models.TextField()),
                ('future_rounds', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FundingStrategy',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('business_stage', models.CharField(max_length=100)),
                ('recommended_type', models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('hybrid', 'Hybrid')], max_length=20)),
                ('reasoning', models.TextField()),
                ('readiness_score', models.IntegerField()),
                ('recommendations', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FundingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=255)),
                ('timeframe', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(max_length=100)),
                ('milestones', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorMatch',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('angel', 'Angel'), ('vc', 'VC'), ('bank', 'Bank'), ('government', 'Government'), ('alternative', 'Alternative')], max_length=20)),
                ('focus_industries', models.JSONField(default=list)),
                ('investment_range_min', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_range_max', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stage', models.JSONField(default=list)),
                ('location', models.CharField(max_length=255)),
                ('match_score', models.IntegerField()),
                ('trust_score', models.IntegerField()),
                ('portfolio', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_model', models.JSONField(default=list)),
                ('growth_stage', models.JSONField(default=list)),
                ('revenue_requirement', models.DecimalField(decimal_places=2, max_digits=15)),
                ('geographic_focus', models.JSONField(default=list)),
                ('time_to_decision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanUpdate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('new-program', 'New Program'), ('rate-change', 'Rate Change'), ('deadline', 'Deadline'), ('policy-update', 'Policy Update')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('urgency', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('affected_programs', models.JSONField(default=list)),
                ('action_required', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('programs', models.JSONField(default=list)),
                ('alert_preferences', models.JSONField(default=dict)),
                ('last_notified', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Investor',
        ),
        migrations.RemoveField(
            model_name='loancomparison',
            name='loan_application',
        ),
        migrations.RemoveField(
            model_name='loaneligibility',
            name='loan_application',
        ),
        migrations.DeleteModel(
            name='LoanResearch',
        ),
        migrations.RemoveField(
            model_name='loancomparison',
            name='comparison_score',
        ),
        migrations.RemoveField(
            model_name='loancomparison',
            name='funding_option',
        ),
        migrations.RemoveField(
            model_name='loaneligibility',
            name='eligible',
        ),
        migrations.RemoveField(
            model_name='loaneligibility',
            name='reason',
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='collateral_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='eligibility_criteria',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='personal_guarantee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='processing_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='provider',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='type',
            field=models.CharField(choices=[('bank-loan', 'Bank Loan'), ('government-grant', 'Government Grant'), ('microfinance', 'Microfinance'), ('angel-capital', 'Angel Capital'), ('venture-capital', 'Venture Capital'), ('crowdfunding', 'Crowdfunding'), ('cooperative', 'Cooperative')], default='bank-loan', max_length=20),
        ),
        migrations.AddField(
            model_name='fundingoption',
            name='website',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='approval_odds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='conditions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='cons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='loan_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='processing_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='pros',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='provider',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='term_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loancomparison',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='business_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='business_stage',
            field=models.CharField(choices=[('startup', 'Startup'), ('early', 'Early'), ('growth', 'Growth'), ('mature', 'Mature')], default='startup', max_length=20),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='collateral_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='eligibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='monthly_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='qualified_programs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='time_in_business',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loaneligibility',
            name='yearly_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundingoption',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fundingoption',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fundingoption',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fundingoption',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fundingoption',
            name='term_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='loancomparison',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loaneligibility',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
    ]
