# Generated by Django 5.2.6 on 2025-09-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('macro', 'Macro'), ('market', 'Market'), ('industry', 'Industry'), ('financial', 'Financial')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('previousValue', models.FloatField()),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=10)),
                ('changePercent', models.FloatField()),
                ('lastUpdated', models.DateField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('forecast', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalPolicy',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('government', 'Government'), ('international', 'International'), ('trade', 'Trade'), ('regulatory', 'Regulatory')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('draft', 'Draft'), ('expired', 'Expired')], max_length=20)),
                ('effectiveDate', models.DateField()),
                ('jurisdiction', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('businessAreas', models.JSONField()),
                ('complianceDeadline', models.DateField(blank=True, null=True)),
                ('lastUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalImpact',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('economicIndicator', models.CharField(max_length=255)),
                ('businessArea', models.CharField(max_length=255)),
                ('impactType', models.CharField(choices=[('revenue', 'Revenue'), ('costs', 'Costs'), ('operations', 'Operations'), ('strategy', 'Strategy')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('description', models.TextField()),
                ('quantifiedImpact', models.JSONField()),
                ('mitigationActions', models.JSONField()),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('analyzing', 'Analyzing'), ('mitigating', 'Mitigating'), ('monitored', 'Monitored')], max_length=20)),
                ('lastAssessed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalPolicy',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('compliance', 'Compliance'), ('operational', 'Operational'), ('hr', 'HR'), ('financial', 'Financial'), ('environmental', 'Environmental')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('draft', 'Draft'), ('archived', 'Archived')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('approvedBy', models.CharField(max_length=255)),
                ('lastReviewed', models.DateField()),
                ('nextReview', models.DateField()),
                ('alignmentScore', models.FloatField()),
                ('relatedExternalPolicies', models.JSONField()),
                ('implementationStatus', models.CharField(choices=[('fully_implemented', 'Fully Implemented'), ('partial', 'Partial'), ('planning', 'Planning'), ('not_started', 'Not Started')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyReport',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('alignment', 'Alignment'), ('compliance', 'Compliance'), ('gap_analysis', 'Gap Analysis'), ('impact_assessment', 'Impact Assessment')], max_length=20)),
                ('generatedDate', models.DateField()),
                ('period', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('findings', models.JSONField()),
                ('complianceScore', models.FloatField()),
                ('recommendations', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRecommendation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('policy_adaptation', 'Policy Adaptation'), ('economic_mitigation', 'Economic Mitigation'), ('opportunity_leverage', 'Opportunity Leverage'), ('risk_management', 'Risk Management')], max_length=30)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('description', models.TextField()),
                ('expectedOutcome', models.TextField()),
                ('timeline', models.CharField(max_length=100)),
                ('resources', models.JSONField()),
                ('success_metrics', models.JSONField()),
                ('dependencies', models.JSONField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('on_hold', 'On Hold')], max_length=20)),
                ('assignedTo', models.CharField(max_length=255)),
                ('estimatedCost', models.FloatField()),
                ('expectedROI', models.FloatField()),
            ],
        ),
    ]
