# Generated by Django 5.2.6 on 2025-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadStock',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField()),
                ('dateIdentified', models.DateField()),
                ('disposalPlan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('forecastedDemand', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('lastUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DisruptionRisk',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('riskType', models.CharField(choices=[('supply_chain', 'Supply Chain'), ('logistics', 'Logistics'), ('market', 'Market'), ('regulatory', 'Regulatory'), ('natural_disaster', 'Natural Disaster')], max_length=20)),
                ('description', models.TextField()),
                ('probability', models.FloatField()),
                ('impact', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('mitigation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('auditDate', models.DateField()),
                ('auditor', models.CharField(max_length=255)),
                ('findings', models.JSONField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('scheduled', 'Scheduled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('raw_materials', 'Raw Materials'), ('finished_goods', 'Finished Goods'), ('work_in_progress', 'Work in Progress'), ('packaging', 'Packaging'), ('spare_parts', 'Spare Parts')], max_length=20)),
                ('unit', models.CharField(max_length=50)),
                ('currentStock', models.IntegerField()),
                ('reorderPoint', models.IntegerField()),
                ('unitCost', models.FloatField()),
                ('supplier', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('lastUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('valuationMethod', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('weighted_average', 'Weighted Average')], max_length=20)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('distribution_center', 'Distribution Center')], max_length=20)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsMetric',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('metricType', models.CharField(choices=[('on_time_delivery', 'On-Time Delivery'), ('order_accuracy', 'Order Accuracy'), ('inventory_accuracy', 'Inventory Accuracy'), ('shipping_cost', 'Shipping Cost')], max_length=20)),
                ('value', models.FloatField()),
                ('period', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketVolatility',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('market', models.CharField(max_length=255)),
                ('volatilityIndex', models.FloatField()),
                ('date', models.DateField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=255)),
                ('items', models.JSONField()),
                ('orderDate', models.DateField()),
                ('expectedDelivery', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryCompliance',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('regulation', models.CharField(max_length=255)),
                ('complianceStatus', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('pending_review', 'Pending Review')], max_length=20)),
                ('lastChecked', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('movementType', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField()),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contactInfo', models.JSONField()),
                ('rating', models.FloatField()),
                ('leadTime', models.IntegerField()),
                ('terms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityMetric',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('metricType', models.CharField(choices=[('carbon_footprint', 'Carbon Footprint'), ('waste_reduction', 'Waste Reduction'), ('energy_efficiency', 'Energy Efficiency'), ('water_usage', 'Water Usage')], max_length=20)),
                ('value', models.FloatField()),
                ('period', models.CharField(max_length=100)),
                ('target', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TurnoverMetric',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('turnoverRate', models.FloatField()),
                ('lastCalculated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOperation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('operationType', models.CharField(choices=[('receiving', 'Receiving'), ('picking', 'Picking'), ('packing', 'Packing'), ('shipping', 'Shipping')], max_length=20)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('operator', models.CharField(max_length=255)),
            ],
        ),
    ]
