# Generated by Django 5.2.6 on 2025-09-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('AUDIT', 'Audit Report'), ('REGULATORY', 'Regulatory Compliance'), ('INTERNAL', 'Internal Review'), ('FINANCIAL', 'Financial Compliance')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('UNDER_REVIEW', 'Under Review'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('report_date', models.DateField()),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('findings', models.JSONField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('INCOME', 'Income Tax'), ('SALES', 'Sales Tax'), ('PROPERTY', 'Property Tax'), ('PAYROLL', 'Payroll Tax'), ('VAT', 'VAT')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('filing_status', models.CharField(choices=[('PENDING', 'Pending'), ('FILED', 'Filed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
