# Generated by Django 5.2.6 on 2025-09-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('cash_inflow', models.FloatField()),
                ('cash_outflow', models.FloatField()),
                ('net_cash_flow', models.FloatField()),
                ('cumulative_cash', models.FloatField()),
                ('working_capital', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CostStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('COGS', 'COGS'), ('Operating', 'Operating')], max_length=10)),
                ('amount', models.FloatField()),
                ('percentage', models.FloatField()),
                ('variability', models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable'), ('Semi-Variable', 'Semi-Variable')], max_length=15)),
                ('trend', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('stable', 'stable')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('demand_assumption', models.IntegerField()),
                ('growth_rate', models.FloatField()),
                ('retention', models.IntegerField()),
                ('avg_order_value', models.FloatField()),
                ('seasonality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current', models.FloatField()),
                ('target', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('trend', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('stable', 'stable')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('projected', models.FloatField()),
                ('conservative', models.FloatField()),
                ('optimistic', models.FloatField()),
                ('actual_to_date', models.FloatField(blank=True, null=True)),
                ('confidence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('Best Case', 'Best Case'), ('Base Case', 'Base Case'), ('Worst Case', 'Worst Case')], max_length=20)),
                ('revenue', models.FloatField()),
                ('costs', models.FloatField()),
                ('profit', models.FloatField()),
                ('probability', models.FloatField()),
                ('key_assumptions', models.JSONField()),
            ],
        ),
    ]
