# Generated by Django 5.2.6 on 2025-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('revenue', models.FloatField()),
                ('customers', models.IntegerField()),
                ('avg_order_value', models.FloatField()),
                ('acquisition_cost', models.FloatField()),
                ('profitability', models.FloatField()),
                ('growth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ChurnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(max_length=100)),
                ('discount_rate', models.FloatField()),
                ('usage', models.FloatField()),
                ('revenue_impact', models.FloatField()),
                ('conversion_lift', models.FloatField()),
                ('margin_impact', models.FloatField()),
                ('customer_segment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('change', models.FloatField()),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=10)),
                ('period', models.CharField(max_length=50)),
                ('benchmark', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('probability', models.FloatField()),
                ('timeframe', models.CharField(max_length=50)),
                ('total_revenue', models.FloatField()),
                ('revenue_growth', models.FloatField()),
                ('key_assumptions', models.JSONField()),
                ('risks', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RevenueStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('subscription', 'Subscription'), ('one-time', 'One-time'), ('usage-based', 'Usage-based'), ('commission', 'Commission'), ('advertising', 'Advertising')], max_length=20)),
                ('current_revenue', models.FloatField()),
                ('forecast_revenue', models.FloatField()),
                ('growth', models.FloatField()),
                ('margin', models.FloatField()),
                ('customers', models.IntegerField()),
                ('avg_revenue_per_customer', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UpsellOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('current_plan', models.CharField(max_length=100)),
                ('suggested_plan', models.CharField(max_length=100)),
                ('current_mrr', models.FloatField()),
                ('potential_mrr', models.FloatField()),
                ('probability_score', models.FloatField()),
                ('time_to_upgrade', models.IntegerField()),
                ('triggers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ChurnAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('churn_rate', models.FloatField()),
                ('customers', models.IntegerField()),
                ('revenue_at_risk', models.FloatField()),
                ('average_lifetime', models.FloatField()),
                ('retention_cost', models.FloatField()),
                ('churn_reasons', models.ManyToManyField(to='revenue_strategy.churnreason')),
            ],
        ),
    ]
